filter:
    excluded_paths:
        - 'tests/*'
        - 'vendor/*'

checks:
    php: true

tools:
    php_code_sniffer:
        enabled: true
        config:
            standard: "PSR2"
        filter:
            excluded_paths:
                - 'tests/*'
                - 'vendor/*'

    php_cs_fixer:
        enabled: true
        config:
            level: psr2
        filter:
            excluded_paths:
                - 'tests/*'
                - 'vendor/*'
